config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  get '/home' => 'home#index', as: 'home'

  resources :sessions, :resources, :payment_methods, :online_sales, :prizes, :products, :scout_site_sales

  get 'signup', to: 'scouts#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'forgot_password', to: 'scouts#forgot_password', as: 'forgot_password'
  post 'reset_password', to: 'scouts#forget_password_send', as: 'reset_password'

  get 'take-orders-order' => 'take_orders_order#index', as: 'take_orders_order'

  get 'ledgers/transactions' => 'ledgers#transactions', as: :ledger_transactions
  get 'ledgers/fund-site-sales' => 'ledgers#fund_site_sales', as: :fund_site_sales
  post 'ledgers/fund-site-sales' => 'ledgers#fund_site_sales'
  get 'ledgers/bank-deposit' => "ledgers#new_bank_deposit", as: 'new_bank_deposit'
  post 'ledgers/bank-deposit' => 'ledgers#create_bank_deposit'
  get 'ledgers/expense-reimbursement-1' => "ledgers#expense_reimbursement_1", as: 'expense_reimbursement_1'
  post 'ledgers/expense-reimbursement-1' => 'ledgers#expense_reimbursement_1'
  get 'ledgers/expense-reimbursement-2' => "ledgers#expense_reimbursement_2", as: 'expense_reimbursement_2'
  post 'ledgers/expense-reimbursement-2' => 'ledgers#expense_reimbursement_2'
  get 'ledgers/collect-from-customer' => "ledgers#collect_from_customer", as: 'collect_from_customer'
  post 'ledgers/collect-from-customer' => 'ledgers#collect_from_customer'

  resources :ledgers

  resources :due_from_customers, only: :index

  get 'events/:id/commissions' => 'events#edit_commission_percentage', as: 'edit_commission_percentage'

  get "product-preset-collections" => 'products#preset_collections', as: 'preset_product_collections'
  post "product-preset-collections" => 'products#add_preset_collection', as: 'add_presets'

  get "reports/summary" => 'reports#summary', as: 'summary_report'

  resources :prize_carts, only: [:index, :show], path: 'prize-carts'
  post 'prize-cart/order' => 'prize_carts#order', as: 'prize_cart_order'
  post 'prize-carts/:id' => 'prize_carts#order_prizes', as: 'order_prizes'
  get 'approved-prizes' => 'prize_carts#approved_prizes', as: 'approved_prizes'
  post "approve-prize-cart/:id" => "prize_carts#approve", as: 'approve_prize_cart'
  post "unapprove-prize-cart/:id" => "prize_carts#unapprove", as: 'unapprove_prize_cart'
  post "prize-cart/removal/:id" => "prize_carts#removal", as: 'prize_removal'
  post "unorder-prize-cart/:id" => "prize_carts#unorder", as: 'unorder_prize_cart'
  patch "envelopes/assign" => "envelopes#assign", as: 'assign_to_envelope'
  post "envelopes/:id/close" => "envelopes#close", as: 'close_envelope'
  post "envelopes/:id/open" => "envelopes#open", as: 'open_envelope'
  post "envelopes/:id/picked-up" => "envelopes#picked_up", as: 'picked_up_envelope'
  put "envelopes/:envelope_id/remove-take-order/:id" => "envelopes#remove_take_order", as: 'envelope_remove_take_order'
  resources :envelopes do
    resources :take_orders
  end
  get "ledgers/statements/balance-sheet" => "ledgers#balance_sheet", as: 'balance_sheet'
   get "ledgers/final-unit-settlement-form" => "ledgers#final_unit_settlement_form", as: 'final_unit_settlement_form'
  get "ledgers/statements/income-statement" => "ledgers#income_statement", as: 'income_statement'

  get 'home/invite_scouts' => 'home#invite_scouts', as: 'invite_scouts'

  resources :units, except: :index
  resources :scouts do
    get 'update-password' => 'scouts#update_password', as: 'update_password'
  end
  resources :site_sales, path: 'site-sales' do
    get "tracking_sheet" => "site_sales#tracking_sheet", as: 'tracking_sheet'
    resources :site_sale_payment_methods, except: :index
    resources :site_sale_line_items
    resources :scout_site_sales
  end

  # get "take-orders/pick-sheet" => 'take_orders#pick_sheet' as: :print_take_order_pick_sheet
  resources :take_orders, path: 'take-orders' do
    resources :take_order_line_items
  end
  get "sstocks/inventory-returnstocks/ledger" => "stocks#ledger", as: 'stocks_ledger'
  get "stocks/stock-transfer-form" => "stocks#stock_transfer_form", as: 'stock_transfer_form'
  get "stocks/stock-transfers-report" => "stocks#stock_transfers_report", as: 'stock_transfers_report'
  post "stocks/stock-transfers-report" => "stocks#stock_transfers_report", as: 'stock_transfers_report_date'
  get "stocks/bsa-transfers-report" => "stocks#bsa_transfers_report", as: 'bsa_transfers_report'


  resources :stocks
  resources :events do
    get 'activate' => 'events#activate', as: 'activate'
    resources :scout_site_sales
    resources :resources
  end

  resources :top_sellers, only: :index
  resources :purchase_orders, :take_order_purchase_orders
  resources :summary_orders, :sales_credits
  post "sales-credits-assignment" => "sales_credits#assignment", as: :sales_credit_assignment

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if @active_event

      @top_sellers = @active_event.sales_by_scout_ordered[0..(@active_event.number_of_top_sellers-1)]
      @resources = @active_event.resources
    

      # Site Sales
      @site_sales = @active_event.upcoming_site_sales


      if current_scout.is_admin?
        # _my_sales - admin
        @take_order_sales_turned_in = @active_event.total_take_order_sales(true)
        @take_order_sales_not_turned_in = @active_event.total_take_order_sales(false)
        @online_sales = @active_event.total_online_sales
        @site_sale_sales = @active_event.total_site_sale_sales
        @total_sales = @active_event.total_sales
        
        @site_sales_cash = Ledger.joins(:account).where('accounts.id = ?', Account.site_sale(@active_event).id).sum('ledgers.amount') if current_scout.is_site_sales_admin?
        @take_orders_cash = Ledger.joins(:account).where('accounts.id = ?', Account.take_order(@active_event).id).sum('ledgers.amount') if current_scout.is_take_orders_admin?
      else
        # _my_sales
        @take_order_sales_turned_in = current_scout.total_take_order_sales( @active_event, true )
        @take_order_sales_not_turned_in = current_scout.total_take_order_sales( @active_event, false )
        @site_sale_sales = @active_event.total_site_sale_sales(current_scout, true)
        @online_sales = current_scout.total_online_sales(@active_event)
        @total_sales = current_scout.total_sales(@active_event)
      end

      @prizes = @active_event.prizes.order(sales_amount: :asc).limit(10)
    end
  end

  def invite_scouts
  end

end

app/views/home/_important_dates.haml
- if @active_event && @active_event.important_dates?
  .card.important_dates
    .card-body
      %h5.card-title Important Dates

      %ul.important_dates.card-text
        - if @active_event.take_orders_deadline_at && @active_event.is_take_orders_enabled
          %li
            Take orders end:
            = @active_event.take_orders_deadline_at.strftime("%b %e")
        - if @active_event.prize_cart_ordering_starts_at && @active_event.prize_cart_ordering_ends_at && @active_event.is_prizes_enabled
          %li
            Prize ordering:
            = @active_event.prize_cart_ordering_starts_at.strftime("%b %-d")
            = '-'
            = @active_event.prize_cart_ordering_ends_at.strftime("%b %-d")

  %br

app/views/home/_my_sales.haml
- if @active_event
  .card
    .card-block
      %h2.card-title.my-sales
        - if current_scout.is_admin?
          Sales
        - else
          My Sales
      
      - grand_total = 0
      %table.table.card-text.table-sm
        - if @active_event.is_take_orders_enabled?
     
          %tr
            %th(colspan=3) Take Orders

          %tr
            %td
            %th
              = link_to "Turned in", take_orders_path
            %td.text-right
              = number_to_currency(@take_order_sales_turned_in, precision: 0)
          %tr
            %td
            %th
              = link_to "Not turned in", take_orders_path
            %td.text-right
              = number_to_currency(@take_order_sales_not_turned_in, precision: 0)

        - if @active_event.is_online_enabled?
          %tr
            %th.online_sales(colspan=2)
              = link_to "Online Sales", online_sales_path
            %td.text-right.online_sales_amount
              = number_to_currency(@online_sales, precision: 0)  


        - if @active_event.is_site_sales_enabled?
          %tr
            %th.site_sales(colspan=2)
              = link_to "Site Sales", site_sales_path
            %td.text-right
              = number_to_currency(@site_sale_sales, precision: 0)      
    
        %tr
          %th(colspan=2) Total Sales
          %td.text-right
            = number_to_currency(grand_total, precision: 0)

app/views/home/_prizes.haml
- if @active_event && @active_event.is_prizes_enabled? && @active_event.prizes?
  .card
    .card-body
      .card-title
        = image_tag 'despic_me_happy.gif', class: "img-fluid"
        %br
        %br
        %h5.text-center
          Prizes to Earn



      %table.table.table-sm.card-text
        %tr.small
          %td Prize
          %td.text-right Sales level
        - @prizes.each do |prize|
          %tr
            %td= prize.name
            %td.text-right= number_to_currency(prize.sales_amount)

      - if @active_event.prize_cart_ordering_starts_at && @active_event.prize_cart_ordering_starts_at < Time.now && @active_event.prize_cart_ordering_ends_at > Time.now
        %hr
        %div.card-text
          = link_to prize_cart_path(current_scout.prize_cart(@active_event)) do
            Order prizes
            %i.fa.fa-long-arrow-right
            %i.fa.fa-shopping-cart
            Prize Cart
    .card-footer.text-center
      = link_to "See all Prizes", prizes_path
  %br

app/views/home/_resources.haml
- if @active_event && @resources.any?
  .card
    .card-body
      %h5.card-title.resources More info

      %ul.card-text
        - @resources.each do |resource|
          %li.resource
            = link_to resource.url do
              = resource.name
              %i.fa.fa-external-link

app/views/home/_sales.haml
- if @active_event
  .card
    .card-body
      %h2.card-title.my-sales
        - if current_scout.is_admin?
          Sales
        - else
          My Sales
      
      - grand_total = 0
      %table.table.card-text.table-sm
        - if @active_event.is_take_orders_enabled?
     
          %tr
            %th.take_orders(colspan=2)= link_to "Take Orders", take_orders_path
            %td.text-right
              = number_to_currency(@take_order_sales_turned_in, precision: 0)
          / %tr
          /   %td 
          /   %th
          /     = link_to "Not turned in", take_orders_path
          /   %td.text-right
          /     = number_to_currency(@take_order_sales_not_turned_in, precision: 0)

        - if @active_event.is_online_enabled?
          %tr
            %th.online_sales(colspan=2)
              = link_to "Online Sales", online_sales_path
            %td.text-right.online_sales_amount
              = number_to_currency(@online_sales, precision: 0)  

        - if @active_event.is_site_sales_enabled?
          %tr
            %th.site_sales(colspan=2)
              = link_to "Site Sales", site_sales_path
            %td.text-right.site-sales-amount
              = number_to_currency(@site_sale_sales, precision: 0)      
    
        %tr
          %td(colspan=2) Total Sales
          %td.text-right
            = number_to_currency(@total_sales, precision: 0)

app/views/home/_selling-tips.haml
.card.text-white.bg-warning.mb-3
  .card-body
    .selling-tips.card-text
      %h3 SELLING TIPS
      %ul
        %li
          %strong Be Neat
          = '- always wear your uniform'
        %li
          %strong Be Prepared
          = '- know your products and what you are going to say'

        %li
          %strong Maintain Eye Contact
          = '- be confident'

        %li
          %strong Speak Loudly & Clearly

        %li
          %strong Always Be Polite & Courteous

        %li
          %strong Thank Everyone
          = "- even the people who don't buy anything"

        %li
          %strong Keep Moving
          = '- the more people you approach and talk to, the more popcorn you will sell'

        %li
          %strong Keep Smiling

app/views/home/_set_up_prizes.haml
.card
  .card-body
    .card-text
      
      .important
        %i.fa.fa-exclamation-circle
        &nbsp;Important!
      Your
      = @active_event.name
      event does not have any prizes and your event has been configured to offer prizes. You can add prizes on the
      = link_to "Prizes page", prizes_path
      individually, or you can load a preset group of prizes.

app/views/home/_set_up_products.haml
.card
  .card-body
    .card-text
      
      .important
        %i.fa.fa-exclamation-circle
        &nbsp;Important!
      Your
      = @active_event.name
      event does not have any popcorn product. You can add products to the
      = link_to "Popcorn Catalog", products_path
      individually, or you can load a preset group of products.

app/views/home/_site_sales.haml
- if @active_event
  .card
    .card-body
      %h5.card-title.site-sales Site Sales Upcoming

      - if @site_sales.any?
        %table.table.card-text.table-sm
          - @site_sales.each do |site_sale|
            %tr
              %td.site_sale_date= site_sale.date.strftime('%b %-d')
              %td.site_sale_name= site_sale.name
      - else
        %p.card-text No Site Sales have been scheduled.
    .card-footer.text-center
      = link_to "View Site Sales", site_sales_path

app/views/home/_site_sales_cash.haml
- if current_scout.is_site_sales_admin?
  .card.site_sales_cash
    .card-body
      %h5.card-title Site Sales Cash

      %p.card-text
        Balance:
        = number_to_currency(@site_sales_cash)

      - if @site_sales_cash > 0
        %p.card-text.small
          Please deposit cash as soon as possible and record the deposit in
          = succeed(".") do
            = Rails.configuration.application_name
          An email notification will be sent to your Unit Treasurer.
        %p.card-text  
          = link_to "Record a deposit", new_bank_deposit_path

app/views/home/_top_sellers.haml
- if @active_event && @active_event.number_of_top_sellers && @active_event.number_of_top_sellers > 0 && @active_event.show_top_sellers
  .card
    .card-header
      %h4.text-center.top-sellers
        %i.fa.fa-trophy.fa-lg
        Top Sellers
        %i.fa.fa-trophy.fa-lg    
    .card-body
      - if @top_sellers.any?
        
        .table-responsive
          %table.table.card-text.table-sm
            - @top_sellers.each do |top_seller|
              - scout = Scout.find(top_seller[0].id)
              %tr
                %td= scout.name
                %td.text-right= number_to_currency(top_seller[1], precision: 0)
      - else
        %p.card-text.alert.alert-info.text-muted.text-center
          %i.fa.fa-info-circle
          We will post the 
          = @active_event.number_of_top_sellers
          top selling Scouts here!          

app/views/home/_upcoming_site_sales.haml
- if @active_event
  .card
    .card-block
      %h5.card-title Site Sales Upcoming

      - if @site_sales.any?
        %table.table.card-text.table-sm
          - @site_sales.each do |site_sale|
            %tr
              %td.site_sale_date= site_sale.date.strftime('%b %-d')
              %td.site_sale_name= site_sale.name
      - else
        %p.card-text No Site Sales have been scheduled.
    .card-footer.text-center
      = link_to "View Site Sales", site_sales_path

app/views/home/index.haml
- if @active_event

  - if current_scout.is_unit_admin? && !@active_event.products?
    .row
      .col-md-12
        = render 'set_up_products'

  - if ( current_scout.is_unit_admin? || current_scout.is_prizes_admin? ) && !@active_event.prizes? && @active_event.is_prizes_enabled?
    .row
      .col-md-12
        = render 'set_up_prizes'

.row
  .col-md-4
    - if current_scout.admin?
      = render 'get_started' unless @active_event && @active_event.set_up?
    = render 'sales'
    = image_tag "scout-sales-script.jpg", class: 'img-fluid img-rounded m-x-auto'
  .col-md-4

    - if @active_event
      = render 'top_sellers'
      = render 'prizes'
      = render 'site_sales_cash'
      = render 'take_orders_cash'
  .col-md-4
    - if @active_event
      - if @active_event.is_site_sales_enabled?
        = render 'site_sales'
      = render 'important_dates'
      / = render 'quick_links'
      = render 'selling-tips'
      = render 'resources'

app/views/home/invite_scouts.haml
.row
  .col-md-4
    .card
      .card-body
        %p Once you have configured your Unit and created an Event, you can invite Scouts to register.