config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  get '/home' => 'home#index', as: 'home'

  resources :sessions, :resources, :payment_methods, :online_sales, :prizes, :products, :scout_site_sales

  get 'signup', to: 'scouts#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'forgot_password', to: 'scouts#forgot_password', as: 'forgot_password'
  post 'reset_password', to: 'scouts#forget_password_send', as: 'reset_password'

  get 'take-orders-order' => 'take_orders_order#index', as: 'take_orders_order'

  get 'ledgers/transactions' => 'ledgers#transactions', as: :ledger_transactions
  get 'ledgers/fund-site-sales' => 'ledgers#fund_site_sales', as: :fund_site_sales
  post 'ledgers/fund-site-sales' => 'ledgers#fund_site_sales'
  get 'ledgers/bank-deposit' => "ledgers#new_bank_deposit", as: 'new_bank_deposit'
  post 'ledgers/bank-deposit' => 'ledgers#create_bank_deposit'
  get 'ledgers/expense-reimbursement-1' => "ledgers#expense_reimbursement_1", as: 'expense_reimbursement_1'
  post 'ledgers/expense-reimbursement-1' => 'ledgers#expense_reimbursement_1'
  get 'ledgers/expense-reimbursement-2' => "ledgers#expense_reimbursement_2", as: 'expense_reimbursement_2'
  post 'ledgers/expense-reimbursement-2' => 'ledgers#expense_reimbursement_2'
  get 'ledgers/collect-from-customer' => "ledgers#collect_from_customer", as: 'collect_from_customer'
  post 'ledgers/collect-from-customer' => 'ledgers#collect_from_customer'

  resources :ledgers

  resources :due_from_customers, only: :index

  get 'events/:id/commissions' => 'events#edit_commission_percentage', as: 'edit_commission_percentage'

  get "product-preset-collections" => 'products#preset_collections', as: 'preset_product_collections'
  post "product-preset-collections" => 'products#add_preset_collection', as: 'add_presets'

  get "reports/summary" => 'reports#summary', as: 'summary_report'

  resources :prize_carts, only: [:index, :show], path: 'prize-carts'
  post 'prize-cart/order' => 'prize_carts#order', as: 'prize_cart_order'
  post 'prize-carts/:id' => 'prize_carts#order_prizes', as: 'order_prizes'
  get 'approved-prizes' => 'prize_carts#approved_prizes', as: 'approved_prizes'
  post "approve-prize-cart/:id" => "prize_carts#approve", as: 'approve_prize_cart'
  post "unapprove-prize-cart/:id" => "prize_carts#unapprove", as: 'unapprove_prize_cart'
  post "prize-cart/removal/:id" => "prize_carts#removal", as: 'prize_removal'
  post "unorder-prize-cart/:id" => "prize_carts#unorder", as: 'unorder_prize_cart'
  patch "envelopes/assign" => "envelopes#assign", as: 'assign_to_envelope'
  post "envelopes/:id/close" => "envelopes#close", as: 'close_envelope'
  post "envelopes/:id/open" => "envelopes#open", as: 'open_envelope'
  post "envelopes/:id/picked-up" => "envelopes#picked_up", as: 'picked_up_envelope'
  put "envelopes/:envelope_id/remove-take-order/:id" => "envelopes#remove_take_order", as: 'envelope_remove_take_order'
  resources :envelopes do
    resources :take_orders
  end
  get "ledgers/statements/balance-sheet" => "ledgers#balance_sheet", as: 'balance_sheet'
   get "ledgers/final-unit-settlement-form" => "ledgers#final_unit_settlement_form", as: 'final_unit_settlement_form'
  get "ledgers/statements/income-statement" => "ledgers#income_statement", as: 'income_statement'

  get 'home/invite_scouts' => 'home#invite_scouts', as: 'invite_scouts'

  resources :units, except: :index
  resources :scouts do
    get 'update-password' => 'scouts#update_password', as: 'update_password'
  end
  resources :site_sales, path: 'site-sales' do
    get "tracking_sheet" => "site_sales#tracking_sheet", as: 'tracking_sheet'
    resources :site_sale_payment_methods, except: :index
    resources :site_sale_line_items
    resources :scout_site_sales
  end

  # get "take-orders/pick-sheet" => 'take_orders#pick_sheet' as: :print_take_order_pick_sheet
  resources :take_orders, path: 'take-orders' do
    resources :take_order_line_items
  end
  get "sstocks/inventory-returnstocks/ledger" => "stocks#ledger", as: 'stocks_ledger'
  get "stocks/stock-transfer-form" => "stocks#stock_transfer_form", as: 'stock_transfer_form'
  get "stocks/stock-transfers-report" => "stocks#stock_transfers_report", as: 'stock_transfers_report'
  post "stocks/stock-transfers-report" => "stocks#stock_transfers_report", as: 'stock_transfers_report_date'
  get "stocks/bsa-transfers-report" => "stocks#bsa_transfers_report", as: 'bsa_transfers_report'


  resources :stocks
  resources :events do
    get 'activate' => 'events#activate', as: 'activate'
    resources :scout_site_sales
    resources :resources
  end

  resources :top_sellers, only: :index
  resources :purchase_orders, :take_order_purchase_orders
  resources :summary_orders, :sales_credits
  post "sales-credits-assignment" => "sales_credits#assignment", as: :sales_credit_assignment

end

app/models/scout.rb
class Scout < ApplicationRecord
  has_secure_password

  belongs_to :unit
  belongs_to :event, optional: true
  has_many :envelopes
  has_many :take_orders, through: :envelopes
  has_many :events, through: :unit
  has_many :site_sales, through: :scout_site_sales
  has_many :scout_site_sales
  has_many :online_sales
  has_many :prize_carts, dependent: :destroy
  has_many :sales_credits
  has_many :sales_credit_totals

  validates :first_name, :last_name, :unit_id, presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :email, uniqueness: { case_sensitive: false }
  validate :must_have_one_unit_admin, if: Proc.new {|s| s.is_unit_admin_changed? && s.is_unit_admin == false}, on: :update

  before_save :fix_name!
  before_validation :downcase_email!
  before_save :set_event!
  after_create :send_registration_email!
  after_create :send_you_are_registered_email!, unless: Proc.new {|s| s.is_admin?}
  # after_create :create_prize_cart!
  before_save :update_is_admin!

  def name
    first_name + ' ' + last_name
  end

  def last_first_name
    last_name + ', ' + first_name
  end

  def self.admin
    where(is_financial_admin: true).or(Scout.where(is_take_orders_admin: true)).or(Scout.where(is_site_sales_admin: true)).or(Scout.where(is_prizes_admin: true)).or(Scout.where(is_admin: true)).or(Scout.where(is_warehouse_admin: true)).or(Scout.where(is_online_sales_admin: true))
  end

  def self.not_admin
    where(is_admin: false)
  end

  def self.active
    where(is_active: true)
  end

  def self.inactive
    where(is_active: false)
  end

  def total_bsa_prize_amounts(event)
    prize_cart(event).cart_prizes.joins(:prize).where("prizes.source = 'bsa'").sum(:prize_amount)
  end

  def prize_cart(event)
    prize_carts.where(event_id: event.id).first || prize_carts.create(event_id: event.id)
  end

  def total_sales(event)
    total = event.total_site_sale_sales(self, true)
    total += total_take_order_sales(event)
    total += total_online_sales(event)
    total
  end

  def sales(event=nil)
    total_sales(event)
  end

  def sales_credit_balance(event)
    sales_credits.where(event_id: event.id).sum(:amount)
  end

  def admin?
    [
      is_financial_admin, 
      is_take_orders_admin, 
      is_site_sales_admin,
      is_prizes_admin,
      is_warehouse_admin,
      is_unit_admin,
      is_online_sales_admin
    ].include? true
  end

  def activity?
    if scout_site_sales.any? || online_sales.any? || take_orders.any?
      true
    else
      false
    end
  end

  def take_order_credits(event, is_turned_in=true)
    if is_turned_in
      take_orders.where("envelopes.event_id = ?",event.id).where.not(status: 'in hand').inject(0){|sum,t| sum + t.take_order_line_items.sum(:value) }
    elsif is_turned_in == false
      take_orders.where("envelopes.event_id = ?",event.id).where(status: 'in hand').inject(0){|sum,t| sum + t.take_order_line_items.sum(:value) }
    else
      take_orders.where("envelopes.event_id = ?",event.id).inject(0){|sum,t| sum + t.take_order_line_items.sum(:value) }
    end
  end

  def total_online_sales(event)
    online_sales.where(event_id: event.id).sum(:amount)
  end

  def total_take_order_sales(event, is_turned_in=true)
    take_order_credits(event, is_turned_in)
  end

  def set_event!
    self.event_id = unit.events.active.last.id if unit.events && unit.events.active && unit.events.active.last
  end

  def event_site_sale_hours_worked(event)
    scout_site_sales.joins(:site_sale).where("site_sales.event_id = ?",event.id).sum(:hours_worked)
  end

  def open_envelope(event)
    open = envelopes.open.where(event_id: event.id).last
    unless open
      open = envelopes.create(event_id: event.id)
    end
    open
  end

  def open_envelope?(event)
    envelopes.open.where(event_id: event.id).any?
  end

  def create_prize_cart!
    prize_carts.create(event_id: @active_event) unless prize_carts.any?
  end

  def assign_full_rights!
    self.is_unit_admin = true
    self.is_take_orders_admin = true
    self.is_site_sales_admin = true
    self.is_online_sales_admin = true
    self.is_prizes_admin = true
    self.is_financial_admin = true
    self.is_warehouse_admin = true
    self.save
  end

  def event_sales_credits(event)
    totals = sales_credits.where(event_id: event.id).sum(:amount)
  end

  private

  def fix_name!
    self.first_name = first_name.capitalize if first_name
    self.last_name = last_name.capitalize if last_name
  end

  def send_registration_email!
    Thread.new do
      ScoutMailer.registration(self.id).deliver_now!
    end
  end

  def send_you_are_registered_email!
    Thread.new do
      ScoutMailer.you_are_registered(self.id).deliver_now!
    end
  end

  def update_is_admin!
    if admin?
      self.is_admin = true
    else
      self.is_admin = false
    end
  end

  def must_have_one_unit_admin
    if unit.scouts.where(is_unit_admin: true).size == 1
      errors.add(:unit_admin, "must be selected since there are no other unit administrators currently.")
    end
  end

  def downcase_email!
    self.email = email.downcase if email
  end

end

app/controllers/scouts_controller.rb
class ScoutsController < ApplicationController
  before_action :set_scout, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:new, :create, :forgot_password, :forget_password_send]
  before_action :authorize_unit_admin, only: :destroy
  before_action :authorize_admin, only: :index

  def index
    @scouts = @unit.scouts.active.not_admin.order(:first_name)
    @administrators = @unit.scouts.active.admin
  end

  def show
  end

  def new
    redirect_to root_path if Unit.active.empty?
    @scout = Scout.new
    @units = Unit.active.order(:name)
  end

  def edit
  end

  def create
    @scout = Scout.new(scout_params)
    @scout.email = @scout.email.downcase

    if current_scout && @scout.save
      redirect_to root_path, notice: 'The account was successfully created.'
    elsif @scout.save
      redirect_to root_path, notice: 'Your account was successfully created. Please login to continue'
    else
      @units = Unit.active.order(:name)
      render :new
    end

  end

  def update_password
    @scout = @unit.scouts.find(params[:scout_id])
  end

  def update
    if ( current_scout.is_unit_admin || current_scout == @scout ) && @scout.update(scout_params)
      redirect_to scout_path(@scout), notice: 'Scout was successfully updated.'
    else
      render :edit, notice: 'Scout was not updated.'
    end
  end

  def destroy
    if @scout.activity?
      message = 'This Scout can not be destroyed since it has activity.'
    else
      @scout.destroy
      if @scout.admin?
        message = 'Administrator account was successfully destroyed.'
      else
        message = 'Scout account was successfully destroyed.'
      end
    end
    redirect_to scouts_path, notice: message
  end

  def forgot_password
  end

  def forget_password_send
    @scout = Scout.find_by_email(params[:email])
    if @scout
      ForgetPasswordMailer.forget(@scout.id).deliver_now!
      redirect_to root_path, notice: "We sent you a password reset email."
    else
      redirect_to root_path, alert: "We don't seem to recognize that email address."
    end
  end

  private
    def set_scout
      @scout = @unit.scouts.find(params[:id])
    end

    def scout_params
      params.require(:scout).permit(:first_name, :last_name, :email, :password, :password_confirmation, :event_id, :is_active, :is_site_sales_admin, :is_take_orders_admin, :is_online_sales_admin, :is_admin, :is_unit_admin, :is_financial_admin, :is_prizes_admin, :is_warehouse_admin, :password_digest, :unit_id)
    end
end

app/views/scouts/_email_taken.haml
.row
  .col-md-9
    .card
      .card-body
        %p.email_taken.card-text
          %i.fa.fa-exclamation-circle.fa-lg.important &nbsp;Important
          The email your are trying to signup with is already used on an account. If you have forgotten your password or possibly your account was set up for you, simply visit the
          = link_to 'Forgot password', forgot_password_path
          page to reset the password and access your account.

app/views/scouts/_form.html.haml
.row
  .col-md-5
    .card
      .card-body
        .card-title
          %h2
            - if @scout.new_record?
              Scout
            - else
              = @scout.name
        = form_for @scout do |f|
          - if @scout.errors.any?
            #error_explanation
              %h2= "#{pluralize(@scout.errors.count, "error")} prohibited this scout from being saved:"
              %ul
                - @scout.errors.full_messages.each do |msg|
                  %li= msg

          %br
          .form-group
            = f.label :first_name
            = f.text_field :first_name, class: 'form-control'
          .form-group
            = f.label :last_name
            = f.text_field :last_name, class: 'form-control'

          - if @scout.new_record?
            .form-group
              = f.label :password
              = f.password_field :password, class: 'form-control'
            .form-group
              = f.label :password_confirmation
              = f.password_field :password_confirmation, class: 'form-control'

          - if current_scout.unit.events.active.size > 1
            .form-group.event_selection
              = f.label :event
              - if current_scout.admin?
                %span= link_to "(New Event)", new_event_path
              = f.collection_select :event_id, @unit.events.order(:name), :id, :name, {:include_blank => "Please select"}, class: 'form-control'

          .form-group
            = f.label :email
            = f.text_field :email, class: 'form-control'
      

          - if current_scout.is_unit_admin?
            .form-check
              .form-check-label
                = f.check_box :is_active, class: 'form-check-input'   
                = f.label :active

            .form-check
              .form-check-label
                = f.check_box :is_unit_admin, class: 'form-check-input' , disabled: current_scout.is_unit_admin? ? false : true
                = f.label :unit_admin

            .form-check
              .form-check-label
                = f.check_box :is_financial_admin, class: 'form-check-input' , disabled: current_scout.is_unit_admin? ? false : true
                = f.label :financial_admin

            .form-check
              .form-check-label
                = f.check_box :is_take_orders_admin, class: 'form-check-input', disabled: current_scout.is_unit_admin? ? false : true
                = f.label :take_orders_admin

            .form-check
              .form-check-label
                = f.check_box :is_site_sales_admin, class: 'form-check-input' , disabled: current_scout.is_unit_admin? ? false : true                
                = f.label :site_sales_admin

            .form-check
              .form-check-label
                = f.check_box :is_online_sales_admin, class: 'form-check-input' , disabled: current_scout.is_unit_admin? ? false : true
                = f.label :online_sales_admin

            .form-check
              .form-check-label
                = f.check_box :is_prizes_admin, class: 'form-check-input' , disabled: current_scout.is_unit_admin? ? false : true
                = f.label :prizes_admin

            .form-check
              .form-check-label
                = f.check_box :is_warehouse_admin, class: 'form-check-input' , disabled: current_scout.is_unit_admin? ? false : true
                = f.label :warehouse_admin

          .actions
            = f.submit 'Save', class: 'btn btn-success'

        %br
        %p= link_to "Change password", scout_update_password_path(current_scout)

app/views/scouts/edit.html.haml
%h1 Scout

= render 'form'

= link_to 'Show', @scout
\|
= link_to 'Back', scouts_path

app/views/scouts/forgot_password.haml
.row
  .col-md-3
  .col-md-6
    .card
      .card-body
        %h4.card-title
          = Rails.configuration.application_name
          Password Reset
        %p.card-text
          = form_tag reset_password_path do
            %br
            .form-group
              = label_tag "Email"
              = text_field_tag :email,"", placeholder: 'Your email address to reset', class: 'form-control'
            .actions
              = submit_tag 'Reset password', class: 'btn btn-success', id: 'site_sale_form_submit'

app/views/scouts/index.html.haml
.row
  .col-md-12

    %h3 Scouts / Administrators

    %ul.nav.nav-tabs.card-text
      %li.nav-item
        = link_to scouts_path(active: true), class: "nav-link #{'active' if params[:active] || (params[:administrators].blank? && params[:inactive].blank?) }" do
          Scouts
          = surround("(", ")") do
            = @scouts.length
      %li.nav-item
        = link_to scouts_path(administrators: true), class: "nav-link #{'active' if params[:administrators]}" do
          Administrators
          = surround("(", ")") do
            = @administrators.length      
    %br
    - unless params[:administrators].present?
      .table-responsive
        %table.table.card-text.table-sm
          %thead
            %tr.small
              %th
              %th
              %th Take Orders
              %th Site Sales
              %th Online
              %th Total
              
              - if current_scout.is_unit_admin?
                %th.text-center Logins
                %th.d-print-none

          %tbody
            - @scouts.each do |scout|
              %tr
                %td
                  %i.fa.fa-user
                  = link_to scout.name, scout_path(scout)
                %td= scout.email
                %td
                  - unless scout.is_admin? || @active_event.nil?
                    = link_to number_to_currency(scout.total_take_order_sales(@active_event), precision: 0), take_orders_path(scout_id: scout.id)
                %td
                  - unless scout.is_admin? || @active_event.nil?
                    = link_to number_to_currency(@active_event.total_site_sale_sales(scout, true), precision: 0), site_sales_path(scout_id: scout.id)
                %td
                  - unless scout.is_admin? || @active_event.nil?
                    = link_to number_to_currency(scout.total_online_sales(@active_event), precision: 0), online_sales_path(scout_id: scout.id)
                %td
                  - unless scout.is_admin? || @active_event.nil?
                    = number_to_currency(scout.sales(@active_event), precision: 0)
                
                - if current_scout.is_unit_admin?
                  %td.text-center= scout.sign_in_count
                  %td.d-print-none
                    = link_to edit_scout_path(scout) do
                      %span.fa.fa-pencil.fa-lg
                    - unless scout.activity?
                      = link_to scout, :method => :delete, :data => { :confirm => 'Are you sure? This will destroy the Scout account and all related information if there is no activity.'  } do
                        %span.fa.fa-trash.fa-lg
                
    - if params[:administrators].present?
      .table-responsive
        %table.table.card-text.table-sm
          %thead.small
            %tr
              %th
              %th
              %th.text-center(colspan=5) RIGHTS
              %th

              - if current_scout.is_unit_admin?
                %th
                %th.d-print-none
            %tr
              %th
              %th.role.text-center Unit
              %th.role.text-center Finances
              %th.role.text-center Take Orders
              %th.role.text-center Site Sales
              %th.role.text-center Online Sales
              %th.role.text-center Warehouse
              %th.role.text-center Prizes
              
              - if current_scout.is_unit_admin?
                / %th.text-center Logins
                %th.d-print-none

          %tbody
            - @administrators.each do |scout|
              %tr
                %td
                  %i.fa.fa-user
                  = link_to scout.name, scout_path(scout)
                %td.role.text-center
                  - if scout.is_unit_admin?
                    %i.fa.fa-check-square-o
                  - else
                    %i.fa.fa-square-o.text-muted
                %td.role.text-center
                  - if scout.is_financial_admin?
                    %i.fa.fa-check-square-o
                  - else
                    %i.fa.fa-square-o.text-muted
                %td.role.text-center
                  - if scout.is_take_orders_admin?
                    %i.fa.fa-check-square-o
                  - else
                    %i.fa.fa-square-o.text-muted
                %td.role.text-center
                  - if scout.is_site_sales_admin?
                    %i.fa.fa-check-square-o
                  - else
                    %i.fa.fa-square-o.text-muted
                %td.role.text-center
                  - if scout.is_online_sales_admin?
                    %i.fa.fa-check-square-o
                  - else
                    %i.fa.fa-square-o.text-muted
                %td.role.text-center
                  - if scout.is_warehouse_admin?
                    %i.fa.fa-check-square-o
                  - else
                    %i.fa.fa-square-o.text-muted
                %td.role.text-center
                  - if scout.is_prizes_admin?
                    %i.fa.fa-check-square-o
                  - else
                    %i.fa.fa-square-o.text-muted
                
                - if current_scout.is_unit_admin?
                  / %td.text-center= scout.sign_in_count
                  %td.d-print-none
                    = link_to edit_scout_path(scout) do
                      %span.fa.fa-pencil.fa-lg
                    - unless scout.activity?
                      = link_to scout, :method => :delete, :data => { :confirm => 'Are you sure? This will destroy the Administrator account and all related information if there is no activity.' } do
                        %span.fa.fa-trash.fa-lg

- if current_scout.is_unit_admin?            
  %br
  .row
    .col-md-3
      .d-print-none
        - if params[:administrators].present?
          = link_to new_scout_path(administrator: true, unit_id: current_scout.unit_id) do
            %i.fa.fa-plus.fa-lg
            Add a new Administrator
        - else
          = link_to new_scout_path(unit_id: current_scout.unit_id) do
            %i.fa.fa-plus.fa-lg
            Add a new Scout

app/views/scouts/new.html.haml
- if @scout.errors.full_messages.include? 'Email has already been taken'
  = render 'email_taken'

.row
  .col-md-6
    .card
      .card-body
        .card-title
          %h2 Sign Up

        - if params[:administrator]
          %p.text-info
            %i.fa.fa-info-circle
            This will initially create a Scout account. Once created, you can add administrative rights to the account.


        = form_for @scout do |f|
          = render 'errors', target: @scout
          
          - if params[:unit_id]
            = f.hidden_field :unit_id, value: params[:unit_id]
          - else
            .form-group
              = f.label :unit
              %br
              = f.collection_select :unit_id, @units, :id, :name, {prompt: 'Select a Unit...'}, class: 'form-control'

          .form-group
            - if params[:administrator]
              = f.label :administrator_email
            - else
              = f.label :email
            %p.small.text-muted
              %i.fa.fa-info-circle
              Your email must not be already in use with another account.
            = f.email_field :email, placeholder: 'Enter email', autofocus: true,  class: 'form-control'
            
          .form-group
            = f.label :scout_first_name
            = f.text_field :first_name, placeholder: 'First name', class: 'form-control'

          .form-group
            = f.label :scout_last_name
            = f.text_field :last_name, placeholder: 'Last name', class: 'form-control'  

          .form-group
            = f.label :password
            - if @minimum_password_length
              %em
                = surround("(", ")") do
                  = @minimum_password_length
                  characters minimum.

            = f.password_field :password, autocomplete: "off",class: 'form-control'

          .form-group
            = f.label :password_confirmation
            = f.password_field :password_confirmation, autocomplete: "off", class: 'form-control'

          .actions
            = f.submit "Sign up", class: 'btn btn-success'

app/views/scouts/show.html.haml
.row
  .col-md-4
    .card
      .card-body
        .card-title
          - if current_scout == @scout || current_scout.is_unit_admin?
            .pull-right
              = link_to edit_scout_path(@scout) do
                %i.fa.fa-pencil
          %h3
            = @scout.name

      %ul.list-group.list-group-flush
        %li.list-group-item
          %i.fa.fa-child.fa-lg
          &nbsp;
          = @scout.name
        %li.list-group-item
          %i.fa.fa-users.fa-lg
          &nbsp;
          = @scout.unit.name
        %li.list-group-item
          %i.fa.fa-calendar.fa-lg
          &nbsp;
          - if @scout.event
            = @scout.event.name
          - else
            - if @scout.unit.events.active.any?
              = link_to "Set Event", edit_scout_path(@scout)
            - else
              No Events available
        %li.list-group-item
          %i.fa.fa-envelope.fa-lg
          &nbsp;
          = @scout.email
        %li.list-group-item
          Last login: 
          = @scout.last_sign_in_at.strftime('%b %d %I:%M%p') if @scout.last_sign_in_at
        - if current_scout.admin?
          - unless @scout.is_active
            %li.list-group-item.text-danger
              %i.fa.fa-exclamation-triangle
              &nbsp;
              ARCHIVED

        - if current_scout == @scout || current_scout.is_unit_admin?
          %li.list-group-item
            = link_to "Change password", scout_update_password_path(@scout)

app/views/scouts/update_password.haml
.row
  .col-md-5
    .card
      .card-body
        %h1.card-title Update Password
        .card-text
          = form_for @scout do |f|
            - if @scout.errors.any?
              #error_explanation
                %h2= "#{pluralize(@scout.errors.count, "error")} prohibited this scout from being saved:"
                %ul
                  - @scout.errors.full_messages.each do |msg|
                    %li= msg

            .form-group
              = f.label :password
              = f.password_field :password, class: 'form-control'
            .form-group
              = f.label :password_confirmation
              = f.password_field :password_confirmation, class: 'form-control'

            .actions
              = f.submit 'Save', class: 'btn btn-success'