config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  get '/home' => 'home#index', as: 'home'

  resources :sessions, :resources, :payment_methods, :online_sales, :prizes, :products, :scout_site_sales

  get 'signup', to: 'scouts#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'forgot_password', to: 'scouts#forgot_password', as: 'forgot_password'
  post 'reset_password', to: 'scouts#forget_password_send', as: 'reset_password'

  get 'take-orders-order' => 'take_orders_order#index', as: 'take_orders_order'

  get 'ledgers/transactions' => 'ledgers#transactions', as: :ledger_transactions
  get 'ledgers/fund-site-sales' => 'ledgers#fund_site_sales', as: :fund_site_sales
  post 'ledgers/fund-site-sales' => 'ledgers#fund_site_sales'
  get 'ledgers/bank-deposit' => "ledgers#new_bank_deposit", as: 'new_bank_deposit'
  post 'ledgers/bank-deposit' => 'ledgers#create_bank_deposit'
  get 'ledgers/expense-reimbursement-1' => "ledgers#expense_reimbursement_1", as: 'expense_reimbursement_1'
  post 'ledgers/expense-reimbursement-1' => 'ledgers#expense_reimbursement_1'
  get 'ledgers/expense-reimbursement-2' => "ledgers#expense_reimbursement_2", as: 'expense_reimbursement_2'
  post 'ledgers/expense-reimbursement-2' => 'ledgers#expense_reimbursement_2'
  get 'ledgers/collect-from-customer' => "ledgers#collect_from_customer", as: 'collect_from_customer'
  post 'ledgers/collect-from-customer' => 'ledgers#collect_from_customer'

  resources :ledgers

  resources :due_from_customers, only: :index

  get 'events/:id/commissions' => 'events#edit_commission_percentage', as: 'edit_commission_percentage'

  get "product-preset-collections" => 'products#preset_collections', as: 'preset_product_collections'
  post "product-preset-collections" => 'products#add_preset_collection', as: 'add_presets'

  get "reports/summary" => 'reports#summary', as: 'summary_report'

  resources :prize_carts, only: [:index, :show], path: 'prize-carts'
  post 'prize-cart/order' => 'prize_carts#order', as: 'prize_cart_order'
  post 'prize-carts/:id' => 'prize_carts#order_prizes', as: 'order_prizes'
  get 'approved-prizes' => 'prize_carts#approved_prizes', as: 'approved_prizes'
  post "approve-prize-cart/:id" => "prize_carts#approve", as: 'approve_prize_cart'
  post "unapprove-prize-cart/:id" => "prize_carts#unapprove", as: 'unapprove_prize_cart'
  post "prize-cart/removal/:id" => "prize_carts#removal", as: 'prize_removal'
  post "unorder-prize-cart/:id" => "prize_carts#unorder", as: 'unorder_prize_cart'
  patch "envelopes/assign" => "envelopes#assign", as: 'assign_to_envelope'
  post "envelopes/:id/close" => "envelopes#close", as: 'close_envelope'
  post "envelopes/:id/open" => "envelopes#open", as: 'open_envelope'
  post "envelopes/:id/picked-up" => "envelopes#picked_up", as: 'picked_up_envelope'
  put "envelopes/:envelope_id/remove-take-order/:id" => "envelopes#remove_take_order", as: 'envelope_remove_take_order'
  resources :envelopes do
    resources :take_orders
  end
  get "ledgers/statements/balance-sheet" => "ledgers#balance_sheet", as: 'balance_sheet'
   get "ledgers/final-unit-settlement-form" => "ledgers#final_unit_settlement_form", as: 'final_unit_settlement_form'
  get "ledgers/statements/income-statement" => "ledgers#income_statement", as: 'income_statement'

  get 'home/invite_scouts' => 'home#invite_scouts', as: 'invite_scouts'

  resources :units, except: :index
  resources :scouts do
    get 'update-password' => 'scouts#update_password', as: 'update_password'
  end
  resources :site_sales, path: 'site-sales' do
    get "tracking_sheet" => "site_sales#tracking_sheet", as: 'tracking_sheet'
    resources :site_sale_payment_methods, except: :index
    resources :site_sale_line_items
    resources :scout_site_sales
  end

  # get "take-orders/pick-sheet" => 'take_orders#pick_sheet' as: :print_take_order_pick_sheet
  resources :take_orders, path: 'take-orders' do
    resources :take_order_line_items
  end
  get "sstocks/inventory-returnstocks/ledger" => "stocks#ledger", as: 'stocks_ledger'
  get "stocks/stock-transfer-form" => "stocks#stock_transfer_form", as: 'stock_transfer_form'
  get "stocks/stock-transfers-report" => "stocks#stock_transfers_report", as: 'stock_transfers_report'
  post "stocks/stock-transfers-report" => "stocks#stock_transfers_report", as: 'stock_transfers_report_date'
  get "stocks/bsa-transfers-report" => "stocks#bsa_transfers_report", as: 'bsa_transfers_report'


  resources :stocks
  resources :events do
    get 'activate' => 'events#activate', as: 'activate'
    resources :scout_site_sales
    resources :resources
  end

  resources :top_sellers, only: :index
  resources :purchase_orders, :take_order_purchase_orders
  resources :summary_orders, :sales_credits
  post "sales-credits-assignment" => "sales_credits#assignment", as: :sales_credit_assignment

end

app/views/resources/_form.html.haml
= form_for @resource do |f|
  - if @resource.errors.any?
    #error_explanation
      %h2= "#{pluralize(@resource.errors.count, "error")} prohibited this resource from being saved:"
      %ul
        - @resource.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :url
    = f.text_field :url, class: 'form-control'
  .actions
    = f.submit 'Save', class: 'btn'

app/views/resources/edit.html.haml
%h1 Editing resource

= render 'form'

= link_to 'Show', @resource
\|
= link_to 'Back', resources_path

app/views/resources/index.haml
.row
  .col-md-12
    .card
      .card-body
        %h3.card-title Resources

        %p.small.text-muted.card-text
          %i.fa.fa-info-circle
          Resources are listed on the dashboard of all Scouts and provide either a link or download of additional information, which could be a prize form, council information etc.

        %table.table.card-text
          - @resources.each do |resource|
            %tr
              %th= resource.name
              %td
                - if resource.url.present?
                  = link_to resource.url, target: '_blank' do
                    = resource.url.truncate(60)
                    %i.fa.fa-external-link
              - if current_scout.is_unit_admin?
                %td
                  = link_to edit_resource_path(resource) do
                    %i.fa.fa-pencil.fa-lg
                  = link_to resource_path(resource), method: :delete do
                    %i.fa.fa-trash.fa-lg


- if current_scout.is_unit_admin?
  .row
    .col-md-6
      .card
        .card-body
          %p.card-text
            = link_to new_resource_path do
              %i.fa.fa-plus.fa-lg
              Add new Resource

app/views/resources/new.html.haml
.row
  .col-md-6
    .card
      .card-body
        .card-title
          %h2 
            New
            = @active_event.name
            resource
        %p.small
          %i.fa.fa-info-circle
          You can add resources for users to link to or download, such as a prize form, instructions etc.

        = render 'form'