config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  get '/home' => 'home#index', as: 'home'

  resources :sessions, :resources, :payment_methods, :online_sales, :prizes, :products, :scout_site_sales

  get 'signup', to: 'scouts#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'forgot_password', to: 'scouts#forgot_password', as: 'forgot_password'
  post 'reset_password', to: 'scouts#forget_password_send', as: 'reset_password'

  get 'take-orders-order' => 'take_orders_order#index', as: 'take_orders_order'

  get 'ledgers/transactions' => 'ledgers#transactions', as: :ledger_transactions
  get 'ledgers/fund-site-sales' => 'ledgers#fund_site_sales', as: :fund_site_sales
  post 'ledgers/fund-site-sales' => 'ledgers#fund_site_sales'
  get 'ledgers/bank-deposit' => "ledgers#new_bank_deposit", as: 'new_bank_deposit'
  post 'ledgers/bank-deposit' => 'ledgers#create_bank_deposit'
  get 'ledgers/expense-reimbursement-1' => "ledgers#expense_reimbursement_1", as: 'expense_reimbursement_1'
  post 'ledgers/expense-reimbursement-1' => 'ledgers#expense_reimbursement_1'
  get 'ledgers/expense-reimbursement-2' => "ledgers#expense_reimbursement_2", as: 'expense_reimbursement_2'
  post 'ledgers/expense-reimbursement-2' => 'ledgers#expense_reimbursement_2'
  get 'ledgers/collect-from-customer' => "ledgers#collect_from_customer", as: 'collect_from_customer'
  post 'ledgers/collect-from-customer' => 'ledgers#collect_from_customer'

  resources :ledgers

  resources :due_from_customers, only: :index

  get 'events/:id/commissions' => 'events#edit_commission_percentage', as: 'edit_commission_percentage'

  get "product-preset-collections" => 'products#preset_collections', as: 'preset_product_collections'
  post "product-preset-collections" => 'products#add_preset_collection', as: 'add_presets'

  get "reports/summary" => 'reports#summary', as: 'summary_report'

  resources :prize_carts, only: [:index, :show], path: 'prize-carts'
  post 'prize-cart/order' => 'prize_carts#order', as: 'prize_cart_order'
  post 'prize-carts/:id' => 'prize_carts#order_prizes', as: 'order_prizes'
  get 'approved-prizes' => 'prize_carts#approved_prizes', as: 'approved_prizes'
  post "approve-prize-cart/:id" => "prize_carts#approve", as: 'approve_prize_cart'
  post "unapprove-prize-cart/:id" => "prize_carts#unapprove", as: 'unapprove_prize_cart'
  post "prize-cart/removal/:id" => "prize_carts#removal", as: 'prize_removal'
  post "unorder-prize-cart/:id" => "prize_carts#unorder", as: 'unorder_prize_cart'
  patch "envelopes/assign" => "envelopes#assign", as: 'assign_to_envelope'
  post "envelopes/:id/close" => "envelopes#close", as: 'close_envelope'
  post "envelopes/:id/open" => "envelopes#open", as: 'open_envelope'
  post "envelopes/:id/picked-up" => "envelopes#picked_up", as: 'picked_up_envelope'
  put "envelopes/:envelope_id/remove-take-order/:id" => "envelopes#remove_take_order", as: 'envelope_remove_take_order'
  resources :envelopes do
    resources :take_orders
  end
  get "ledgers/statements/balance-sheet" => "ledgers#balance_sheet", as: 'balance_sheet'
   get "ledgers/final-unit-settlement-form" => "ledgers#final_unit_settlement_form", as: 'final_unit_settlement_form'
  get "ledgers/statements/income-statement" => "ledgers#income_statement", as: 'income_statement'

  get 'home/invite_scouts' => 'home#invite_scouts', as: 'invite_scouts'

  resources :units, except: :index
  resources :scouts do
    get 'update-password' => 'scouts#update_password', as: 'update_password'
  end
  resources :site_sales, path: 'site-sales' do
    get "tracking_sheet" => "site_sales#tracking_sheet", as: 'tracking_sheet'
    resources :site_sale_payment_methods, except: :index
    resources :site_sale_line_items
    resources :scout_site_sales
  end

  # get "take-orders/pick-sheet" => 'take_orders#pick_sheet' as: :print_take_order_pick_sheet
  resources :take_orders, path: 'take-orders' do
    resources :take_order_line_items
  end
  get "sstocks/inventory-returnstocks/ledger" => "stocks#ledger", as: 'stocks_ledger'
  get "stocks/stock-transfer-form" => "stocks#stock_transfer_form", as: 'stock_transfer_form'
  get "stocks/stock-transfers-report" => "stocks#stock_transfers_report", as: 'stock_transfers_report'
  post "stocks/stock-transfers-report" => "stocks#stock_transfers_report", as: 'stock_transfers_report_date'
  get "stocks/bsa-transfers-report" => "stocks#bsa_transfers_report", as: 'bsa_transfers_report'


  resources :stocks
  resources :events do
    get 'activate' => 'events#activate', as: 'activate'
    resources :scout_site_sales
    resources :resources
  end

  resources :top_sellers, only: :index
  resources :purchase_orders, :take_order_purchase_orders
  resources :summary_orders, :sales_credits
  post "sales-credits-assignment" => "sales_credits#assignment", as: :sales_credit_assignment

end

app/models/unit.rb
class Unit < ApplicationRecord
  has_many :scouts, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :ledgers, through: :accounts

  accepts_nested_attributes_for :scouts

  scope :active, -> { joins(:events).where("events.is_active = ?", true) }

  validates :name, presence: true, uniqueness: true
  validates :treasurer_email, format: /@/, unless: Proc.new {|u| u.treasurer_email.blank? }
  validates :treasurer_first_name, presence: true, unless: Proc.new {|u| u.treasurer_email.blank? }

  def treasurer?
    true unless treasurer_email.blank? || treasurer_first_name.blank?
  end

  def treasurer_name
    (treasurer_first_name || '') + ' ' + (treasurer_last_name || '')
  end

  def admin
    scouts.where(is_unit_admin: true)
  end

end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:new, :create]
  before_action :authorize_unit_admin, only: [:edit, :update, :destroy]

  def show
    cookies[:unit_id] = @unit.id
  end

  def new
    @unit = Unit.new
    @scout = Scout.new
  end

  def edit
  end

  def create
    @unit = Unit.new(unit_params)
    @scout = Scout.new(scout_params)
    @scout.valid?
    @scout.errors.delete(:unit_id)
    @scout.errors.delete(:unit)
    if !@scout.errors.any? && @unit.save
      @scout = @unit.scouts.new(first_name: scout_params[:first_name], last_name: scout_params[:last_name], unit_id: @unit.id, email: scout_params[:email], password:  scout_params[:password], password_confirmation: scout_params[:password_confirmation], is_unit_admin: true)
      @scout.assign_full_rights!
      redirect_to root_path, notice: 'Unit was successfully created. Login to continue.'
    else
      render :new, notice: @unit.errors.full_messages
    end
  end

  def update
    if @unit.update(unit_params)
      redirect_to @unit, notice: 'Unit was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @unit.destroy
    redirect_to root_url, notice: 'Unit was successfully destroyed.'
  end

  private
    def set_unit
      @unit = Unit.find(params[:id])
    end

    def unit_params
      params.require(:unit).permit(:name, :street_address_1, :street_address_2, :city, :zip_code, :state_postal_code, :treasurer_first_name, :treasurer_last_name, :treasurer_email, :first_name, :last_name, :email, :send_email_on_registration, :send_emails)
    end

    def scout_params
      params.require(:scout).permit( :password, :password_confirmation, :first_name, :last_name, :email )
    end
end

app/views/units/_form.html.haml
= form_tag units_path, method: :post do
  - if @unit.errors.any?
    #error_explanation
      %h2= "#{pluralize(@unit.errors.count, "error")} prohibited this unit from being saved:"
      %ul
        - @unit.errors.full_messages.each do |msg|
          %li= msg
  - if @scout.errors.any?
    #error_explanation
      %h2= "#{pluralize(@scout.errors.count, "error")} prohibited this Administrator from being saved:"
      %ul
        - @scout.errors.full_messages.each do |msg|
          %li= msg         

  .form-group
    = label_tag :unit_name
    = text_field :unit, :name, placeholder: 'Enter a Unit name, ex: Pack 999', class: 'form-control'

  %br

  %h5 Administrator

  %p.text-muted.small
    %i.fa.fa-info-circle
    The Administrator will have full rights and can add additional administrators.



  .form-group
    = label_tag :first_name
    = text_field :scout, :first_name, class: 'form-control'

  .form-group
    = label_tag :last_name
    = text_field :scout, :last_name, class: 'form-control'

  .form-group
    = label_tag :email
    = text_field :scout, :email, class: 'form-control'

  .form-group
    = label_tag :password
    - if @minimum_password_length
      %em
        = surround("(", ")") do
          = @minimum_password_length
          characters minimum.

    = password_field :scout, :password, autocomplete: "off",class: 'form-control'

  .form-group
    = label_tag :password_confirmation
    = password_field :scout,:password_confirmation, autocomplete: "off", class: 'form-control'

  .actions
    = submit_tag 'Create Unit', class: 'btn btn-success'

app/views/units/edit.html.haml
.row
  .col-md-6
    .card
      .card-body
        .card-title
          %h2 Unit Details

        = form_for @unit do |f|
          - if @unit.errors.any?
            #error_explanation
              %h2= "#{pluralize(@unit.errors.count, "error")} prohibited this unit from being saved:"
              %ul
                - @unit.errors.full_messages.each do |msg|
                  %li= msg
          
          .form-group
            = f.label :name
            = f.text_field :name, placeholder: 'Pack 999', class: 'form-control'

          %br
          %h4 Email Notifications
          %p.text-muted
            %i.fa.fa-info-circle
            Notifications can be enabled to send a confirmation email to Scouts, and a copy to the Unit administrator, when they register. You can also turn off e-mails altogether.

          .form-check
            .form-check-label
              = f.check_box :send_email_on_registration, class: 'form-check-input'
              = f.label :send_email_on_registration

          .form-check
            .form-check-label
              = f.check_box :send_emails, class: 'form-check-input'
              = f.label :send_emails



          %h4 Treasurer Notifications

          %p.text-muted
            %i.fa.fa-info-circle
            Entering Treasurer details here will result in email notifications of the dates and amounts of money when deposited into a unit bank account.
          .form-group
            = f.label :treasurer_first_name
            = f.text_field :treasurer_first_name, class: 'form-control'
          .form-group
            = f.label :treasurer_last_name
            = f.text_field :treasurer_last_name, class: 'form-control'
          .form-group
            = f.label :treasurer_email
            = f.text_field :treasurer_email, class: 'form-control'

          .actions
            = f.submit 'Save', class: 'btn btn-success'

app/views/units/new.html.haml
.row
  .col-md-3
  .col-md-6
    .card
      .card-body
        %h1.card-title Create a new Scout Unit

        %p.card-text.text-muted.small
          %i.fa.fa-info-circle
          Create a new Scout Unit with an Adminstrator account.


        = render 'form'

app/views/units/show.html.haml
.row
  .col-md-6
    .card

      .card-body
        .card-title
          %h3
            = @unit.name
            - if current_scout.is_unit_admin?
              .pull-right
                = link_to edit_unit_path do
                  %i.fa.fa-pencil

        %table.table
          %tr
            %th Email sent on registration:
            %td.text-right
              - if @unit.send_email_on_registration
                %i.fa.fa-check-square-o.fa-lg
              - else
                %i.fa.fa-square-o.fa-lg
          %tr
            %th Emails:
            %td.text-right
              - if @unit.send_emails
                %i.fa.fa-check-square-o.fa-lg
              - else
                %i.fa.fa-square-o.fa-lg

          %tr
            %th Treasurer:
            %td.text-right= @unit.treasurer_name

          %tr
            %th Treasurer Email:
            %td.text-right= @unit.treasurer_email

          %tr
            %th= link_to "Change Event", events_path
            %td


        - if current_scout.is_unit_admin?
          .text-xs-center
            = link_to @unit, :method => :delete, class: 'btn btn-danger', :data => { :confirm => 'WARNING - Are you sure? This will result in your Unit and all event information to be deleted, including your adminstrator account. This action in NON-RECOVERABLE!' } do
              %i.fa.fa-trash-o
              DESTROY UNIT